### ISSUE TITLE
Dll from process

### ISSUE THREAD

**Issue by jBZ8hwBS1QS** [ivan-sincek/invoker#1]
You just build an cascaded injector and first inject into a 3rd Party Process and the 2nd injector in the 3rd Party process wait for the csgo process and attach to it and look for the loaded panorma environemnt. If it has been loaded the 2nd injector in the 3rd Party Process can inject into csgo process. That is what most p2c Developers do with their injectors. VAC can not scan the 3rd Party harmless application because it is out of scope. I have already successfully injected with Nvidia Stuff which attach/inject into nearly any 3D Application.

Can I get this? From invoker

**Comment by ivan-sincek** [comment]
Hi,

Sorry for the really late response, I have been busy with other stuff...

I am also sorry to inform you that unfortunately my expertise is not game hack and cheat development and I really do not understand what you would like me to do...

Maybe, if you give me a little more information, I can look into it but I can't promise anything.

Best regards,
Ivan.

**Comment by ivan-sincek** [comment]
I will close this issue.
